# appling some Code from "Nueral Network from scratch in python" Book

In [1]:
!sudo apt-get install python3.7.7
! pip install numpy==1.18.2
! pip install matplotlib==3.2.1

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.7.7
E: Couldn't find any package by glob 'python3.7.7'
E: Couldn't find any package by regex 'python3.7.7'
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 10.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 MB 20.6 MB/s eta 0:00:00
  Preparin

In [2]:
!pip install nnfs

### first neural network

In [3]:
import numpy as np
import matplotlib
import math

In [4]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(outputs)


35.7


### appling weights as Book

In [5]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(outputs)


2.3


In [6]:
# adding one more input
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(outputs)


4.8


In [7]:
# using 3 neurons

inputs1=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=2
bias2=3
bias3=0.5

outputs=[inputs1[0]*weights1[0]+inputs1[1]*weights1[1]+inputs1[2]*weights1[2]+inputs1[3]*weights1[3]+bias1,
         inputs1[0]*weights2[0]+inputs1[1]*weights2[1]+inputs1[2]*weights2[2]+inputs1[3]*weights2[3]+bias2,
         inputs1[0]*weights3[0]+inputs1[1]*weights3[1]+inputs1[2]*weights3[2]+inputs1[3]*weights[3]+bias3]
print(outputs)




[4.8, 1.21, 2.71]


### Dot product

In [8]:

inputs1=[1,2,3,2.5]
weight=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

layer_outputs =[]

for neuron_weights ,neuron_bias in zip(weight,bias):
  neuron_output=0

  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output+= n_input*weight

  neuron_output+=neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


In [9]:
inputs=[1,2,3,2.5]
weight=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(inputs,weight)+bias
print(output)


4.8


In [10]:

inputs=[1,2,3,2.5]
weight=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

output1=np.dot(weight,inputs)+bias

print(output1)


[4.8   1.21  2.385]


### Batches, Layers, and Objects

In [11]:

inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weight=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

output1=np.dot(inputs,np.array(weight).T)+bias

print(output1)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [12]:
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weight=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]
# second layer
weight2=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]

layer1=np.dot(inputs,np.array(weight).T)+bias
layer2_output=np.dot(layer1,np.array(weight2).T)+bias2

print(layer2_output)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [13]:
np.random.seed(0)
class Layer_Dense:
  def __init__(self, n_inputs , n_neurons):
    self.weights= 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases= np.zeros((1,n_neurons))

  def forward(self, inputs):
    self.outputs=np.dot(inputs,self.weights)+self.biases

In [14]:
X=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

Layer1=Layer_Dense(4, 5)

Layer2=Layer_Dense(5,2)

Layer1.forward(X)
Layer2.forward(Layer1.outputs)
print(Layer2.outputs)


[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


### Hidden Layer Activation Functions

In [15]:
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]

for i in inputs:
  output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [16]:
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

In [17]:
class Activation_ReLU:
  def forward(self,inputs):
    self.outputs=np.max(0,inputs)


In [18]:
#create data
X,y= spiral_data(100,3)
#NN
layer1=Layer_Dense(2,5)
activation1= Activation_ReLU()

layer1.forward(X)
layer1.outputs
#activation1.forward(layer1.outputs)

print(layer1.outputs)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.00080274 -0.00204304  0.00065987 -0.00100411  0.00083796]
 [ 0.00082768 -0.00286869  0.0005103  -0.00076876  0.00454176]
 ...
 [ 0.01800099 -0.09704996  0.00336391 -0.00459795  0.26602511]
 [-0.08834392  0.16360456 -0.08628659  0.13192221  0.20328078]
 [-0.02497925 -0.0066356  -0.03620114  0.05579987  0.31271706]]


### Softmax Activation

In [19]:
layer_output=[[4.8,1.21,2.385],
              [8.9,-1.8,0.2],
              [1.41,1.051,0.026]]
#E=math.e
exp_values=np.exp(layer_output)

#normalize values
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)



print(norm_values)
print(sum(norm_values))

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99810905e-01 2.25406748e-05 1.66554310e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
[2.40819073 0.38306475 0.20874452]


In [20]:
class Activation_Softmax:
  def forward(self, inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities

In [21]:
dense1=Layer_Dense(2,3)
activ1=Activation_ReLU()

dense2=Layer_Dense(3,3)
activ2=Activation_Softmax()

dense1.forward(X)
activ1.forward(dense1.outputs)
dense2.forward(activ1.outputs)
activ2.forward(dense2.outputs)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

### Calculating Loss with Categorical Cross-Entropy

In [22]:
softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]

loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])

print(loss)

0.35667494393873245


In [24]:
softmax_output=np.array([[0.7,0.1,0.2],
                        [0.1,0.5,0.4],
                        [0.02,0.9,0.08]])
class_targets=[0,1,1]
print(softmax_output[[0,1,2],class_targets])

[0.7 0.5 0.9]


In [25]:
class Loss:
  def calculate(self,inputs):
    sample_losses=self.forward(output,y)
    data_loss=np.mean(sample_losses)
    return data_loss

class Loss_CategoricalCrossentropy(Loss):
  def forward(self, y_pred, y_true):
    samples=len(y_pred)
    y_pred_clipped=np.clip(y_pred,1e-7,1-1e-7)
    if len(y_true.shape)==1:
      correct_conf=y_pred_clipped[range(samples),y_true]

    elif len(y_true.shape)==2:
      correct_conf=np.sum(y_pred_clipped*y_true,axis=1)

    neg_log_liklihood=np.log(correct_conf)
    return neg_log_liklihood
